name: Deploy to GitHub Pages
on: 
  workflow_dispatch:
  push:
    branches: [main, develop]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter packages get
      
    - name: Build web
      run: flutter build web --release --base-href '/gh_flutter/'
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./build/web